### ISSUE TITLE
Getting negative weight on solr ltr model 

### ISSUE THREAD

**Issue by jaehyunshinML** [o19s/hello-ltr#17]
Hi,

I've been trying solr ltr with custom data.
After my training, some of the model weights turns out negative values. 
does it mean the model diverged?

**Comment by softwaredoug** [comment]
Can you clarify what you mean by negative weights? The model can output negative values...

FYI, if this is Solr specific, you may wish to ask at Solr-user...

**Comment by jaehyunshinML** [comment]
Hi Thank for your reply.

This is the train model. 

{
	"class":"org.apache.solr.ltr.model.LinearModel",
	"store": "exampleFeatureStore",
	"name": "exampleModel",
	"features": [
		{ "name":"productNameMatchQuery"},
		{ "name":"brandNameMatchQuery"},
		{ "name":"CategoryNamePathMatchQuery"},
		{ "name":"CategoryNamePathAnalyzed"},
		{ "name":"popularity"}
	],
	"params": {
		"weights": {
			"productNameMatchQuery":0.0,
			"brandNameMatchQuery":0.0,
			"CategoryNamePathMatchQuery":0.0,
			"CategoryNamePathAnalyzed":0.0,
			"popularity":-0.0074785481691076895
		}
	}
}

After training has done.
The weight of popularity is negative which had not seen any other example model. Do you know why does this mean?

**Comment by softwaredoug** [comment]
Hey @jaehyunshinML. Thanks for your question, though I think this is unrelated to this project. We are just a set of Jupyter notebooks for experimenting with Solr or Elasticsearch LTR, and don't maintain Solr or Elastic LTR here.

Two places that would be best for your question:

- The Solr Mailing List: https://lucene.apache.org/solr/community.html#mailing-lists-irc
- The Search Relevance Slack Room: http://o19s.com/slack

A short answer though is that a negative weight means the feature is negatively correlated with relevance. More popular means less relevant...
