### ISSUE TITLE
Judgement ctor requires doc id to be int

### ISSUE THREAD

**Issue by DmitryKey** [o19s/hello-ltr#18]
https://github.com/o19s/hello-ltr/blob/54ece3b9fc6842f7ed9b20b2366ff4b61d2024ed/ltr/judgments.py#L8

In our product, we use string doc ids, which is convenient and more flexible than int.
With the req above I had to enumerate documents manually before indexing in Solr.

I propose to relax the requirement to string, if there are no issues with that in downstream components.

**Comment by softwaredoug** [comment]
Hey @DmitryKey - @nathancday going to look into changing this and ensuring notebooks still run. We can't remember why that line is there

But if you want to just delete the cast to int, and try things out, please feel free to.
