### ISSUE TITLE
docker-compose.yml for solr uses an ES path

### ISSUE THREAD

**Issue by nathancday** [o19s/hello-ltr#21]
https://github.com/o19s/hello-ltr/blob/21ffd7f57ba5261503aeff9751029122254c7a95/docker/solr/docker-compose.yml#L12

Looks like it might be carry over, plus I'm not sure we even need the `docker/solr/docker-compose.yml`

Should we remove it? Or am I missing something...

**Comment by worleydl** [comment]
This was carry-over and looks to be cleaned up in the recent re-org.
