### ISSUE TITLE
data/rre-evaluation.json is missing

### ISSUE THREAD

**Issue by nathancday** [o19s/hello-ltr#22]
This is used in the `evaluation.ipynb` for demo-ing RRE. Should these scripts be removed? or should that JSON file be re-added?

**Comment by worleydl** [comment]
That file is generated inside of `ltr/evaluate.py` which does some docker magic and copies the results out to the data folder.  Did you run into errors with the call to evaluate in the notebook?

**Comment by nathancday** [comment]
I just stumbled on a file not found I think, but if `data/` has been removed then I guess this is resolved?

**Comment by softwaredoug** [comment]
Just a note, if we think this is working now, we can reenable these notebooks in tests and rerun the tests. Right now they are in "ignored notebooks" in `tests/run_most_nbs.py`. I had thought they were failing in my tests, hence turning them off, but maybe it's a simple thing to fix

**Comment by worleydl** [comment]
The tests are working here, do you have any error output?
