### ISSUE TITLE
Add additional RankLib flags to the ltr.ranklib training methods

### ISSUE THREAD

**Issue by binarymax** [o19s/hello-ltr#52]
We currently don't support all the command line flags as documented here: https://sourceforge.net/p/lemur/wiki/RankLib%20How%20to%20use/ 

We should evaluate which additional flags to support and add them to the ```ltr.ranklib``` methods of ```trainModel```, ```train```, ```kcv```, and ```feature_search```

At the very least, we should add the ```tc``` flag

**Comment by nathancday** [comment]
Linked #54
