### ISSUE TITLE
Confusion over ltr.train and ltr.ranklib

### ISSUE THREAD

**Issue by binarymax** [o19s/hello-ltr#54]
We have different modules that seemingly do the same thing and it's causing confusion.  See the Netfix movies notebooks, lots of references to ```from ltr import train``` but there is no module ```train```.  There IS a module ltr.ranklib.  We need to figure out and clean up the module dependencies.

**Comment by nathancday** [comment]
Consolidate this to one function with named params/args for exposing anything that ranklib can take. 

As bigger picture we should probably have inherited args from `train` thru `kcv` and `featureSearch`.
