### ISSUE TITLE
Deploying Doubts

### ISSUE THREAD

**Issue by SergioBarretoJr** [o19s/hello-ltr#74]
Good Morning! I'm working on a search improvement project and this plugin meets my demand well, but I have doubts about deploying, because in my case there is no possibility of using python in production.

After training with python and generating the template, can I use the template with Elastic syntax without needing python? If so, do you know where I can get an example or tutorial in this regard?

**Comment by worleydl** [comment]
You can use anything of your choosing to push data into the LTR plugin.  You can also utilize the `ltr` query over `sltr` to provide features at query time however we do not recommend such an approach in production.

This project mostly serves for training and learning purposes, although we cover the basics here and provide two minimal clients for Solr & ES you will typically need to stand up your own pipeline for generating/deploying LTR assets.  Discussion of such matters is out of the scope of this project's issues but we encourage you to join (Relevance Slack)[https://o19s.com/slack] and visit the #es-learn-to-rank channel if you have more general LTR questions.
