### ISSUE TITLE
Starting elasticsearch container failed

### ISSUE THREAD

**Issue by ainkov** [o19s/hello-ltr#8]
Hi there,

I got the following error:

bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
bootstrap checks failed

I guess it's probably related to this (I'm not an es expert): 
https://github.com/elastic/elasticsearch/issues/19987

Fixed it by:
transport.host: localhost

Cheers.

**Comment by worleydl** [comment]
Hi, I'm trying to replicate this.  Can you let me know what OS you were running when you encountered this issue?

Thanks.

**Comment by ainkov** [comment]
Hey,
I'm running Ubuntu 18.04.3 LTS (under VirtualBox).
Docker version 19.03.5.

Cheers.

**Comment by softwaredoug** [comment]
Going to close, but please do reopen if you have any issues
